// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: exchangerates/exchange_rates.proto

package exchangerates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeRatesService_GetExchangeRates_FullMethodName = "/exchangerates.ExchangeRatesService/GetExchangeRates"
)

// ExchangeRatesServiceClient is the client API for ExchangeRatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeRatesServiceClient interface {
	GetExchangeRates(ctx context.Context, in *GetExchangeRatesRequest, opts ...grpc.CallOption) (*GetExchangeRatesResponse, error)
}

type exchangeRatesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeRatesServiceClient(cc grpc.ClientConnInterface) ExchangeRatesServiceClient {
	return &exchangeRatesServiceClient{cc}
}

func (c *exchangeRatesServiceClient) GetExchangeRates(ctx context.Context, in *GetExchangeRatesRequest, opts ...grpc.CallOption) (*GetExchangeRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExchangeRatesResponse)
	err := c.cc.Invoke(ctx, ExchangeRatesService_GetExchangeRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeRatesServiceServer is the server API for ExchangeRatesService service.
// All implementations must embed UnimplementedExchangeRatesServiceServer
// for forward compatibility.
type ExchangeRatesServiceServer interface {
	GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*GetExchangeRatesResponse, error)
	mustEmbedUnimplementedExchangeRatesServiceServer()
}

// UnimplementedExchangeRatesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeRatesServiceServer struct{}

func (UnimplementedExchangeRatesServiceServer) GetExchangeRates(context.Context, *GetExchangeRatesRequest) (*GetExchangeRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExchangeRates not implemented")
}
func (UnimplementedExchangeRatesServiceServer) mustEmbedUnimplementedExchangeRatesServiceServer() {}
func (UnimplementedExchangeRatesServiceServer) testEmbeddedByValue()                              {}

// UnsafeExchangeRatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeRatesServiceServer will
// result in compilation errors.
type UnsafeExchangeRatesServiceServer interface {
	mustEmbedUnimplementedExchangeRatesServiceServer()
}

func RegisterExchangeRatesServiceServer(s grpc.ServiceRegistrar, srv ExchangeRatesServiceServer) {
	// If the following call pancis, it indicates UnimplementedExchangeRatesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeRatesService_ServiceDesc, srv)
}

func _ExchangeRatesService_GetExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeRatesServiceServer).GetExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeRatesService_GetExchangeRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeRatesServiceServer).GetExchangeRates(ctx, req.(*GetExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeRatesService_ServiceDesc is the grpc.ServiceDesc for ExchangeRatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeRatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchangerates.ExchangeRatesService",
	HandlerType: (*ExchangeRatesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRates",
			Handler:    _ExchangeRatesService_GetExchangeRates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchangerates/exchange_rates.proto",
}
